// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Chat = { id: string, username: string, name: string, remark?: string, lastMessagePreview?: string, lastMessageSender?: string, lastActivityAt?: string, unreadCount: number, isGroup: boolean, lastMsgLocalId?: number, };
