// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OpenChatResult = { ok: boolean, username?: string, index?: number, error?: string, };
