// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileData } from "./FileData";
import type { ImageData } from "./ImageData";

export type SendParams = { chatId: string, text?: string, image?: ImageData, file?: FileData, mentions?: Array<string>, };
