// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LoginSubscriptionEvent = { "type": "status", message: string, } | { "type": "qr", qrData: string, qrBinaryData?: number[], qrDataUrl?: string, } | { "type": "phone_confirm", message?: string, } | { "type": "login_success", userId?: string, } | { "type": "login_timeout" } | { "type": "error", message: string, };
